//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.269
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetsAreDangerous.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetsAreDangerous.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Credits.
        /// </summary>
        internal static string CreditsButton {
            get {
                return ResourceManager.GetString("CreditsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dedicated To:.
        /// </summary>
        internal static string DedicatedToTitle {
            get {
                return ResourceManager.GetString("DedicatedToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a YourName.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Game Over!.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue.
        /// </summary>
        internal static string GameOverButton {
            get {
                return ResourceManager.GetString("GameOverButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HowTo.
        /// </summary>
        internal static string HowToButton {
            get {
                return ResourceManager.GetString("HowToButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How To Play.
        /// </summary>
        internal static string HowToTitle {
            get {
                return ResourceManager.GetString("HowToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idea, programming, drawings, 3D modeling:.
        /// </summary>
        internal static string MadeByTitle {
            get {
                return ResourceManager.GetString("MadeByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tilt your phone to move left and right!.
        /// </summary>
        internal static string MovementText {
            get {
                return ResourceManager.GetString("MovementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Movement.
        /// </summary>
        internal static string MovementTitle {
            get {
                return ResourceManager.GetString("MovementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you really want to exit?.
        /// </summary>
        internal static string MsgBoxExitCaption {
            get {
                return ResourceManager.GetString("MsgBoxExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You will lose all the progress of this match!.
        /// </summary>
        internal static string MsgBoxExitText {
            get {
                return ResourceManager.GetString("MsgBoxExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Original Music:.
        /// </summary>
        internal static string MusicByTitle {
            get {
                return ResourceManager.GetString("MusicByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Music Volume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your time is not a record! Try again!.
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There aren&apos;t scores yet!.
        /// </summary>
        internal static string NoScores {
            get {
                return ResourceManager.GetString("NoScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dodge the dogs and boxes, or you&apos;ll lose life-points! If an obstacle collide with another one, they&apos;ll disappear..
        /// </summary>
        internal static string ObstaclesText {
            get {
                return ResourceManager.GetString("ObstaclesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Obstacles.
        /// </summary>
        internal static string ObstaclesTitle {
            get {
                return ResourceManager.GetString("ObstaclesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Play.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pick up the lightning bolts to keep your speed. If you miss too many of those you&apos;ll stop and the match will end! You&apos;ll need hearts as well if obstacles damage you..
        /// </summary>
        internal static string PowerUpsText {
            get {
                return ResourceManager.GetString("PowerUpsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Back.
        /// </summary>
        internal static string ScoresBackButton {
            get {
                return ResourceManager.GetString("ScoresBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scores.
        /// </summary>
        internal static string ScoresButton {
            get {
                return ResourceManager.GetString("ScoresButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Play with your friends, and see who&apos;s the one who can resist... in the most dangerous street ever!.
        /// </summary>
        internal static string ScoresText {
            get {
                return ResourceManager.GetString("ScoresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scores.
        /// </summary>
        internal static string ScoresTitle {
            get {
                return ResourceManager.GetString("ScoresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound Effects Volume.
        /// </summary>
        internal static string SoundEffectsVolume {
            get {
                return ResourceManager.GetString("SoundEffectsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Thanks to the people who helped me to make my dream come true:.
        /// </summary>
        internal static string ThanksToTitle {
            get {
                return ResourceManager.GetString("ThanksToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vibration:.
        /// </summary>
        internal static string VibrationSettingsLabel {
            get {
                return ResourceManager.GetString("VibrationSettingsLabel", resourceCulture);
            }
        }
    }
}
